import { StyleSheet, TextStyle, ViewStyle, type ImageStyle } from 'react-native'

export const colors = {
  bg: '#f7f4ec',
  surface: '#ffffff',
  surface2: '#f0ece1',
  card: '#ffffff',
  text: '#111111',
  textMuted: '#5a564d',
  border: '#111111',
  accent: '#ffd43b',
  accent2: '#2f6bff',
  accent3: '#ff5a4d',
  danger: '#ff5a4d',
  success: '#16a34a',
}

export const grad = {
  primary: ['#ffd43b', '#2f6bff', '#ff5a4d'] as const,
}

export const shadows = {
  card: {
    shadowColor: '#111111',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  button: {
    shadowColor: '#111111',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  } as ViewStyle,
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: colors.bg,
  } as ViewStyle,
  hero: {
    padding: 24,
    paddingBottom: 12,
  } as ViewStyle,
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 24,
  } as ViewStyle,
  logoIcon: {
    width: 44,
    height: 44,
    borderRadius: 0,
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.card,
  } as ViewStyle,
  logoText: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: -0.4,
    textTransform: 'uppercase',
  } as TextStyle,
  title: {
    fontSize: 30,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: -0.6,
    lineHeight: 34,
    marginBottom: 10,
    textTransform: 'uppercase',
  } as TextStyle,
  subtitle: {
    fontSize: 17,
    color: colors.textMuted,
    lineHeight: 25,
    marginBottom: 28,
  } as TextStyle,
  sectionLabel: {
    fontSize: 14,
    fontWeight: '900',
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    paddingHorizontal: 24,
    marginBottom: 14,
  } as TextStyle,
  button: {
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.border,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    ...shadows.button,
  } as ViewStyle,
  buttonOutline: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
  } as ViewStyle,
  buttonText: {
    color: '#111111',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  } as TextStyle,
  buttonTextOutline: {
    color: colors.text,
  } as TextStyle,
  input: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 0,
    padding: 16,
    fontSize: 17,
    color: colors.text,
    marginBottom: 16,
  } as TextStyle,
  card: {
    backgroundColor: colors.card,
    padding: 18,
    borderRadius: 0,
    marginBottom: 14,
    borderWidth: 2,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shadows.card,
  } as ViewStyle,
  cardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  } as ViewStyle,
  cardThumb: {
    width: 50,
    height: 50,
    borderRadius: 0,
    backgroundColor: colors.surface2,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  } as ViewStyle,
  cardTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.text,
  } as TextStyle,
  cardSub: {
    fontSize: 15,
    color: colors.textMuted,
    marginTop: 3,
  } as TextStyle,
  cardArrow: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  } as TextStyle,
  photo: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: 0,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
  } as ImageStyle,
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 56,
  } as ViewStyle,
  emptyIcon: {
    fontSize: 48,
    marginBottom: 16,
    opacity: 0.5,
  } as TextStyle,
  emptyText: {
    fontSize: 17,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 25,
  } as TextStyle,
  statChip: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 0,
    paddingVertical: 8,
    paddingHorizontal: 16,
  } as ViewStyle,
  statChipText: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '700',
  } as TextStyle,
  skeleton: {
    backgroundColor: colors.surface,
    borderRadius: 0,
    borderWidth: 2,
    borderColor: colors.border,
    height: 76,
    marginBottom: 14,
  } as ViewStyle,
})